// Display-math block detection for Math Mode: a per-line classifier feeding a
// linear-chain CRF, decoded with a constrained Viterbi over logical lines.
//
// The greedy $$ pairing this replaces commits to its first reading of each
// delimiter, so one misread (a closing $$ taken for an opener, as when a view
// starts part-way through a document) shifts every pair after it. The CRF
// scores the whole sequence at once, and hard rules become decoding
// constraints: a prompt row or a fenced-code row can only be outside a block.
//
// Trained offline; the weights live in displayMathModel.json. Everything here
// must match the training code exactly -- featurization, attribute names,
// tie-breaking -- which test/displayMathModel.test.js pins with a fixture
// generated by the training pipeline.

const MODEL = require('./displayMathModel.json');

const LABELS = ['O', 'B', 'I', 'E', 'S'];
const CTX_KEYS = ['lr', 'blank', 'prompt', 'dd_bare', 'dd_start', 'dd_end', 'dd_both', 'br_bare_open',
  'br_bare_close', 'fence', 'linebreak', 'amp', 'menv_begin', 'menv_end', 'short'];

const CTRL_RE = /\\[A-Za-z]+/g;
const WORD_RE = /[A-Za-z]+/g;
const NUM_RE = /[0-9]+/g;
const CJK_RE = /[぀-ヿ㐀-䶿一-鿿가-힯豈-﫿]+/g;
const FENCE_RE = /^ {0,3}(`{3,}|~{3,})/;
const AMBIG_CTRL_RE = /\\[A-Za-z]{2,}/;
const MATH_ENVS = '(?:equation|align|alignat|flalign|gather|multline|eqnarray|displaymath|'
  + 'aligned|alignedat|gathered|split|cases|dcases|rcases|matrix|pmatrix|bmatrix|'
  + 'Bmatrix|vmatrix|Vmatrix|smallmatrix|array|subarray|CD)\\*?';
const ENV_TOKEN_RE = new RegExp('\\\\(begin|end)\\{(' + MATH_ENVS + ')\\}', 'g');

// Python's str.strip(): also drops the \x1c-\x1f separators and NEL that JS
// trim() keeps.
function pyStrip(s) {
  return s.replace(/^[\s\x1c-\x1f\x85]+|[\s\x1c-\x1f\x85]+$/gu, '');
}

// control word -> §, letter run -> a, digits -> 0, CJK run -> C, any other
// non-ASCII letter -> u; non-ASCII symbols such as ≤ are kept.
function shape(t) {
  const s = t.replace(CTRL_RE, '§').replace(WORD_RE, 'a').replace(NUM_RE, '0').replace(CJK_RE, 'C');
  let out = '';
  for (const ch of s) {
    out += ch.codePointAt(0) > 0x7f && ch !== '§' && /\p{L}/u.test(ch) ? 'u' : ch;
  }
  return out;
}

// Per-model scratch: dense weights (a lookup per n-gram instead of a Map), a
// reusable count array with the list of buckets it touched, and a cache of
// line scores -- a scrollback barely changes between two Math Mode toggles.
const SCORE_CACHE_MAX = 50000;
let _scratch = null;
function scratchFor(stage1) {
  if (_scratch && _scratch.stage1 === stage1) return _scratch;
  const size = 2 << stage1.bits;
  const weights = new Float64Array(size);
  for (let i = 0; i < stage1.idx.length; i++) weights[stage1.idx[i]] = stage1.w[i];
  _scratch = {
    stage1,
    weights,
    counts: new Uint16Array(size),
    touched: [],
    minN: Math.min(...stage1.ngrams),
    maxN: Math.max(...stage1.ngrams),
    cache: new Map()
  };
  return _scratch;
}

function codePointsOf(str) {
  const out = [];
  for (let i = 0; i < str.length;) {
    const cp = str.codePointAt(i);
    out.push(cp);
    i += cp > 0xffff ? 2 : 1;
  }
  return out;
}

// FNV-1a over each 3..5-code-point window, counted into buckets. The hash of a
// window extends the hash of the window one shorter, so each start position
// costs five steps rather than one hash per n-gram length.
function countNgrams(cps, offset, sc, mask) {
  const { counts, touched, minN, maxN } = sc;
  for (let i = 0; i + minN <= cps.length; i++) {
    let h = 0x811c9dc5;
    for (let k = 0; k < maxN && i + k < cps.length; k++) {
      h ^= cps[i + k];
      h = Math.imul(h, 0x01000193) >>> 0;
      if (k + 1 >= minN) {
        const b = offset + (h & mask);
        if (counts[b]++ === 0) touched.push(b);
      }
    }
  }
}

// Logit of "this line is display-math body" from the line alone.
function scoreLine(text, model = MODEL) {
  const stage1 = model.stage1;
  const sc = scratchFor(stage1);
  const hit = sc.cache.get(text);
  if (hit !== undefined) return hit;
  const dim = 1 << stage1.bits;
  const raw = codePointsOf(text).slice(0, stage1.maxlen);
  countNgrams(raw, 0, sc, dim - 1);
  countNgrams(codePointsOf(shape(String.fromCodePoint(...raw))), dim, sc, dim - 1);
  let norm = 0;
  let dot = 0;
  for (const b of sc.touched) {
    const v = 1 + Math.log(sc.counts[b]);
    norm += v * v;
    dot += sc.weights[b] * v;
    sc.counts[b] = 0;
  }
  sc.touched.length = 0;
  const z = stage1.bias + (norm > 0 ? dot / Math.sqrt(norm) : 0);
  if (sc.cache.size >= SCORE_CACHE_MAX) sc.cache.delete(sc.cache.keys().next().value);
  sc.cache.set(text, z);
  return z;
}

function isLineAmbiguous(text) {
  const s = pyStrip(text);
  return Array.from(s).length < 8 && !AMBIG_CTRL_RE.test(s);
}

function lrBucket(z) {
  const edges = [-6, -3, -1, 1, 3, 6];
  for (let i = 0; i < edges.length; i++) if (z < edges[i]) return i;
  return edges.length;
}

function firstCharClass(c) {
  if (!c) return 'none';
  if (c === '\\') return 'bs';
  if (/\p{L}/u.test(c)) return 'alpha';
  if (/[\p{Nd}²³¹⁰-⁹₀-₉]/u.test(c)) return 'digit';
  return 'sym';
}

function baseAttrs(text, z, prompt) {
  const s = pyStrip(text);
  const a = { bias: 1, lr: Math.max(-8, Math.min(8, z)) / 4 };
  a['lrb' + lrBucket(z)] = 1;
  if (!s) a.blank = 1;
  else if (isLineAmbiguous(text)) a.short = 1;
  if (prompt) a.prompt = 1;
  const st = s.startsWith('$$');
  const en = s.length >= 2 && s.endsWith('$$');
  if (s === '$$') a.dd_bare = 1;
  else if (st && en) a.dd_both = 1;
  else if (st) a.dd_start = 1;
  else if (en) a.dd_end = 1;
  else if (s.includes('$$')) a.dd_mid = 1;
  if (s === '\\[') a.br_bare_open = 1;
  else if (s.startsWith('\\[')) a.br_open = 1;
  if (s === '\\]') a.br_bare_close = 1;
  else if (s.endsWith('\\]')) a.br_close = 1;
  if (s.startsWith('\\begin{')) a.begin = 1;
  if (s.startsWith('\\end{')) a.end = 1;
  for (const m of s.matchAll(ENV_TOKEN_RE)) {
    if (m[1] === 'begin') a.menv_begin = 1;
    else a.menv_end = 1;
  }
  if (s.endsWith('\\\\')) a.linebreak = 1;
  if (s.startsWith('&') || s.includes(' &')) a.amp = 1;
  if (FENCE_RE.test(text)) a.fence = 1;
  a['fc_' + firstCharClass(Array.from(s)[0])] = 1;
  return a;
}

function seqAttrs(texts, zs, prompts) {
  const base = texts.map((t, i) => baseAttrs(t, zs[i], prompts[i]));
  const out = [];
  let inFence = false;
  for (let i = 0; i < base.length; i++) {
    const f = Object.assign({}, base[i]);
    if (inFence && !('fence' in base[i])) f.in_fence = 1;
    if ('fence' in base[i]) inFence = !inFence;
    if (i === 0) f.BOS = 1;
    if (i === base.length - 1) f.EOS = 1;
    for (const off of [-2, -1, 1, 2]) {
      const j = i + off;
      const tag = (off > 0 ? '+' : '') + off;
      if (j >= 0 && j < base.length) {
        for (const k of CTX_KEYS) if (k in base[j]) f[tag + ':' + k] = base[j][k];
      } else {
        f[tag + ':none'] = 1;
      }
    }
    out.push(f);
  }
  return out;
}

// forcedOutside[i]: a prompt or fenced-code row, which may only be 'O'.
function viterbi(attrs, forcedOutside, crf) {
  const n = attrs.length;
  const L = LABELS.length;
  if (!n) return [];
  const emit = new Array(n);
  for (let i = 0; i < n; i++) {
    const e = new Float64Array(L);
    for (const k in attrs[i]) {
      const row = crf.state[k];
      if (!row) continue;
      const v = attrs[i][k];
      for (let y = 0; y < L; y++) e[y] += v * row[y];
    }
    if (forcedOutside[i]) for (let y = 1; y < L; y++) e[y] = -1e9;
    emit[i] = e;
  }
  let score = Float64Array.from(emit[0]);
  const back = new Array(n);
  for (let i = 1; i < n; i++) {
    const next = new Float64Array(L);
    const bp = new Int8Array(L);
    for (let y = 0; y < L; y++) {
      let best = -Infinity; let arg = 0;
      for (let p = 0; p < L; p++) {
        const s = score[p] + crf.transitions[p][y];
        if (s > best) { best = s; arg = p; }
      }
      next[y] = best + emit[i][y];
      bp[y] = arg;
    }
    back[i] = bp;
    score = next;
  }
  let last = 0;
  for (let y = 1; y < L; y++) if (score[y] > score[last]) last = y;
  const path = [last];
  for (let i = n - 1; i > 0; i--) path.push(back[i][path[path.length - 1]]);
  return path.reverse().map(k => LABELS[k]);
}

// Tag runs -> [start, end] index spans. A run may begin with I/E (the view
// starts inside a block) or end with B/I (it stops inside one).
function tagsToSpans(tags) {
  const out = [];
  let start = null;
  for (let i = 0; i < tags.length; i++) {
    const t = tags[i];
    if (t === 'S') {
      if (start !== null) { out.push([start, i - 1]); start = null; }
      out.push([i, i]);
    } else if (t === 'B') {
      if (start !== null) out.push([start, i - 1]);
      start = i;
    } else if (t === 'I' || t === 'E') {
      if (start === null) start = i;
      if (t === 'E') { out.push([start, i]); start = null; }
    } else if (start !== null) {
      out.push([start, i - 1]);
      start = null;
    }
  }
  if (start !== null) out.push([start, tags.length - 1]);
  return out;
}

// texts: logical lines. isPrompt(i) marks shell prompt rows (a model feature
// as well as a constraint); isForcedOutside(i) marks other rows that can never
// be math, such as fenced code. Returns [{ start, end, tags }] in line indices.
function detectDisplayMathSpans(texts, { isPrompt = () => false, isForcedOutside = () => false } = {}, model = MODEL) {
  const prompts = texts.map((_, i) => !!isPrompt(i));
  const forced = texts.map((_, i) => prompts[i] || !!isForcedOutside(i));
  const zs = texts.map(t => scoreLine(t, model));
  const tags = viterbi(seqAttrs(texts, zs, prompts), forced, model.crf);
  return tagsToSpans(tags).map(([start, end]) => ({ start, end, tags: tags.slice(start, end + 1) }));
}

module.exports = {
  LABELS,
  shape,
  scoreLine,
  isLineAmbiguous,
  baseAttrs,
  seqAttrs,
  viterbi,
  tagsToSpans,
  detectDisplayMathSpans
};
